export { default as Categories } from './Categories';
export { default as Dashboard } from './Dashboard';
export { default as Login } from './Login';
export { default as Orders } from './Orders';
export { default as ProductCreate } from './ProductCreate';
export { default as ProductUpdate } from './ProductUpdate';
export { default as Products } from './Products';
export { default as Reviews } from './Reviews';
export { default as Users } from './Users';
