export const orderState = {
    cancel: {
        level: -1,
        state: 'Hủy đơn hàng',
        COD: {
            isPay: 'Chưa thanh toán',
            isCancel: false,
            isDelivery: false,
            isComplete: false,
            state: 'Hủy đơn hàng',
        },
        PAYPAL: {
            isPay: 'Chưa thanh toán',
            isCancel: false,
            isDelivery: false,
            isComplete: false,
            state: 'Hủy đơn hàng',
        },
        VNPAY: {
            isPay: 'Chưa thanh toán',
            isCancel: false,
            isDelivery: false,
            isComplete: false,
            state: 'Hủy đơn hàng',
        },
    },
    enable: {
        level: 0,
        state: 'Trong giỏ hàng',
        COD: {
            isPay: 'Chưa thanh toán',
            isCancel: false,
            isDelivery: false,
            isComplete: false,
            state: 'Trong giỏ hàng',
        },
        PAYPAL: {
            isPay: 'Chưa thanh toán',
            isCancel: false,
            isDelivery: false,
            isComplete: false,
            state: 'Trong giỏ hàng',
        },
        VNPAY: {
            isPay: 'Chưa thanh toán',
            isCancel: false,
            isDelivery: false,
            isComplete: false,
            state: 'Trong giỏ hàng',
        },
    },
    process: {
        level: 1,
        state: 'Đang tiến hành',
        COD: {
            isPay: 'Chưa thanh toán',
            isCancel: true,
            isDelivery: false,
            isComplete: false,
            state: 'Đang tiến hành',
        },
        PAYPAL: {
            isPay: 'Chưa thanh toán',
            isCancel: true,
            isDelivery: false,
            isComplete: false,
            state: 'Đang tiến hành',
        },
        VNPAY: {
            isPay: 'Chưa thanh toán',
            isCancel: true,
            isDelivery: false,
            isComplete: false,
            state: 'Đang tiến hành',
        },
    },
    pendingpay: {
        level: 2,
        state: 'Đã thanh toán và đang xử lý',
        COD: {
            isPay: 'Chưa thanh toán',
            isCancel: true,
            isDelivery: true,
            isComplete: false,
            state: 'Đã thanh toán và đang xử lý',
        },
        PAYPAL: {
            isPay: 'Đã thanh toán',
            isCancel: false,
            isDelivery: true,
            isComplete: false,
            state: 'Đã thanh toán và đang xử lý',
        },
        VNPAY: {
            isPay: 'Đã thanh toán',
            isCancel: false,
            isDelivery: true,
            isComplete: false,
            state: 'Đã thanh toán và đang xử lý',
        },
    },
    pending: {
        level: 3,
        state: 'Đang xử lý',
        COD: {
            isPay: 'Chưa thanh toán',
            isCancel: true,
            isDelivery: true,
            isComplete: false,
            state: 'Đang xử lý',
        },
        PAYPAL: {
            isPay: 'Đã thanh toán',
            isCancel: false,
            isDelivery: true,
            isComplete: false,
            state: 'Đang xử lý',
        },
        VNPAY: {
            isPay: 'Đã thanh toán',
            isCancel: false,
            isDelivery: true,
            isComplete: false,
            state: 'Đang xử lý',
        },
    },
    delivery: {
        level: 4,
        state: 'Đang giao hàng',
        COD: {
            isPay: 'Chưa thanh toán',
            isCancel: true,
            isDelivery: false,
            isComplete: true,
            state: 'Đang giao hàng',
        },
        PAYPAL: {
            isPay: 'Đã thanh toán',
            isCancel: false,
            isDelivery: false,
            isComplete: true,
            state: 'Đang giao hàng',
        },
        VNPAY: {
            isPay: 'Đã thanh toán',
            isCancel: false,
            isDelivery: false,
            isComplete: true,
            state: 'Đang giao hàng',
        },
    },
    complete: {
        level: 5,
        state: 'Giao hàng thành công',
        COD: {
            isPay: 'Đã thanh toán',
            isCancel: false,
            isDelivery: false,
            isComplete: false,
            state: 'Giao hàng thành công',
        },
        PAYPAL: {
            isPay: 'Đã thanh toán',
            isCancel: false,
            isDelivery: false,
            isComplete: false,
            state: 'Giao hàng thành công',
        },
        VNPAY: {
            isPay: 'Đã thanh toán',
            isCancel: false,
            isDelivery: false,
            isComplete: false,
            state: 'Giao hàng thành công',
        },
    },
};
export const contentReviewStates = {
    all: 'Tất cả',
    enable: 'Đã đăng',
    block: 'Bị khóa',
};
export const contentUserStates = {
    all: 'Tất cả',
    active: 'Đã kích hoạt',
    not_verify: 'Chưa xác nhận',
    block: 'Bị khóa',
};
export const contentOrderStates = {
    all: 'Tất cả',
    pending: 'Đang xử lý',
    pendingpay: 'Đã thanh toán và đang xử lý',
    delivery: 'Đang giao hàng',
    complete: 'Đã giao hàng',
    cancel: 'Đã hủy',
};
export const contentProductStates = {
    all: 'Tất cả',
    enable: 'Công bố',
    disable: 'Đã ẩn',
};
