services:
    user:
        image: nginx:1.25.2
        ports:
            - 3000:80
        volumes:
            - ../user_page/build:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
    admin:
        image: nginx:1.25.2
        ports:
            - 3001:80
        volumes:
            - ../admin_page/build:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
