export const home = '/';
export const signIn = '/sign-in';
export const signUp = '/sign-up';
export const search = '/search';
export const cart = '/cart';
export const profile = '/profile';
export const orders = '/orders';
export const checkout = '/checkout';
export const forgotPassword = '/forgot-password';
export const sendOtp = '/send-otp';
export const checkOtp = '/check-otp';
export const checkOtpRegister = '/check-otp-register';
export const resetPassword = '/reset-password';
export const loginAdmin = '/admin/login';
export const addresses = '/addresses';
export const addressForm = '/address-form';
export const product = (id) => `/product/${id}`;
